# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 702ec070a2f4bcd4645793c8f25e25f3affec09a191b1e24bf36306281052550315fc5c324521fa9b7a149f8ce740009caff19054b61ab96a239a07db8bcc947

test:
  secret_key_base: 8b547b939c5ccb1a8d26878e74b0ff9417a406c5f595e85f129e87b392de1c1af1f4d1f59c48dcc58684e681553ee3e7686ab0d69a8086306ee60874a5f5cb0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
